on:
  repository_dispatch:
    types:
      - bootcamp-issue-assigned # repository_dispatch送出時のevent_typeの名前と揃える

jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE >> issue.md
